title: "Anubhav"
author: "KMIT Students"
description: "Classroom blogs where students can share their ideas."

theme: "minima"
github_username: "KMIT-Students"

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: All
  - scope:
      path: README.md
    values:
      sitemap: false
